# syntax=docker/dockerfile:1.4

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["Varnex.AuthService.sln", "./"]
COPY ["nuget.config", "./"]
COPY ["src/Varnex.AuthService.Abstractions/Varnex.AuthService.Abstractions.csproj", "src/Varnex.AuthService.Abstractions/"]
COPY ["src/Varnex.AuthService.Core/Varnex.AuthService.Core.csproj", "src/Varnex.AuthService.Core/"]
COPY ["src/Varnex.AuthService.Api/Varnex.AuthService.Api.csproj", "src/Varnex.AuthService.Api/"]
COPY ["test/Varnex.AuthService.Api.Test/Varnex.AuthService.Api.Test.csproj", "test/Varnex.AuthService.Api.Test/"]
COPY ["test/Varnex.AuthService.Core.Test/Varnex.AuthService.Core.Test.csproj", "test/Varnex.AuthService.Core.Test/"]
COPY ["test/Varnex.AuthService.Integration.Test/Varnex.AuthService.Integration.Test.csproj", "test/Varnex.AuthService.Integration.Test/"]
COPY ["Directory.Build.props", "./"]
COPY ["src/Directory.Build.props", "src/"]
COPY ["test/Directory.Build.props", "test/"]
COPY [".build/", ".build/"]

RUN --mount=type=secret,id=github_token \
    export GITHUB_TOKEN="$(cat /run/secrets/github_token)" && \
    dotnet restore

COPY . .

# We don't publish, we just run the tests from the SDK image
ENTRYPOINT ["dotnet", "test", "test/Varnex.AuthService.Integration.Test/Varnex.AuthService.Integration.Test.csproj", "--logger:trx;LogFileName=integration-results.trx"]


